FOLIO-EIS/ui-linked-data

- src/common/constants/bibframeMapping.constants.ts
[https://folio-org.atlassian.net/browse/UILD-245](https://folio-org.atlassian.net/browse/UILD-245)
> UILD-245: extend mapping for Work Title 

- src/common/constants/feature.constants.ts
- src/components/EditSection/EditSection.scss
- src/components/SimpleLookupField/ClearIndicator.tsx
- src/components/SimpleLookupField/DropdownIndicator.tsx
- src/components/SimpleLookupField/MultiValueRemove.tsx
- src/components/SimpleLookupField/SimpleLookupField.scss
- src/components/SimpleLookupField/SimpleLookupField.styles.ts
- src/components/SimpleLookupField/SimpleLookupField.tsx
[https://folio-org.atlassian.net/browse/UILD-209](https://folio-org.atlassian.net/browse/UILD-209)
> UILD-209: enable simple lookups

- src/common/constants/routes.constants.ts
- src/common/helpers/search.helper.ts
- src/common/hooks/useBackToSearchUri.ts
- src/common/hooks/useLoadSearchResults.ts
- src/common/hooks/useNavigateEditPage.ts
- src/common/hooks/useNavigateToEditPage.ts
- src/common/hooks/useRecordControls.ts
- src/common/hooks/useSearchNavigationState.ts
- src/components/AdvancedSearchModal/AdvancedSearchModal.tsx
- src/components/ItemSearch/ItemSearch.tsx
- src/components/Nav/Nav.tsx
- src/components/SearchControlPane/SearchControlPane.tsx
- src/components/SearchControls/SearchControls.tsx
- src/components/SearchResultEntry/SearchResultEntry.tsx
- src/components/SearchResultList/SearchResultList.tsx
- src/components/WorkDetailsCard/WorkDetailsCard.tsx
- src/state/search.ts
- src/test/__tests__/components/AdvancedSearchModal.test.tsx
- src/test/__tests__/components/SearchControls.test.tsx
- src/test/__tests__/components/SearchResultEntry.test.tsx
- src/types/search.d.ts
[https://folio-org.atlassian.net/browse/UILD-243](https://folio-org.atlassian.net/browse/UILD-243)
> UILD-243: navigate to search results from Edit page

- src/test/__tests__/common/hooks/useBackToSearchUri.test.ts
- src/test/__tests__/common/hooks/useLoadSearchResults.test.ts
- src/test/__tests__/common/hooks/useNavigateToEditPage.test.ts
- src/test/__tests__/common/hooks/useSearchNavigationState.test.ts
[https://folio-org.atlassian.net/browse/UILD-243](https://folio-org.atlassian.net/browse/UILD-243)
> UILD-243: unit tests for transportation to search results

- src/common/hooks/useLoadSearchResults.ts
- src/components/ItemSearch/ItemSearch.tsx
- src/test/__tests__/components/ItemSearch.test.tsx
https://folio-org.atlassian.net/browse/UILD-252
> fix: UILD-252: Marve Search: Pagination does not work correctly for advanced search results

- src/common/constants/bibframeMapping.constants.ts
- src/common/constants/lookup.constants.ts
[https://folio-org.atlassian.net/browse/UILD-197](https://folio-org.atlassian.net/browse/UILD-197)
> UILD-197: Geographic Coverage, Date of Work, Government Publication mapping

- src/common/constants/bibframeMapping.constants.ts
[https://folio-org.atlassian.net/browse/UILD-254](https://folio-org.atlassian.net/browse/UILD-254)
> UILD-254: Intended Audience mapping

- src/common/constants/bibframeMapping.constants.ts
[https://folio-org.atlassian.net/browse/UILD-255](https://folio-org.atlassian.net/browse/UILD-255)
> UILD-255: Place of Origin mapping

- tsconfig.json
- vite.config.ts
[https://folio-org.atlassian.net/browse/UILD-256](https://folio-org.atlassian.net/browse/UILD-256)
> UILD-256: build config fixed

- package-lock.json
- package.json
- src/test/__tests__/components/App.test.tsx
- src/test/setupTests.ts
- tsconfig.json
- vite.config.ts
[https://folio-org.atlassian.net/browse/UILD-256](https://folio-org.atlassian.net/browse/UILD-256)
> UILD-256: failed test fixed

- src/components/EditPreview/EditPreview.tsx
[https://folio-org.atlassian.net/browse/UILD-258](https://folio-org.atlassian.net/browse/UILD-258)
> UILD-258: back to search results from a new Instance

- src/common/constants/bibframeMapping.constants.ts
- src/common/helpers/recordFormatting.helper.ts
- src/common/services/userValues/userValueTypes/simpleLookup.ts
- src/test/__tests__/common/helpers/recordFormatting.helper.test.ts
- src/types/recordProcessing.d.ts
[https://folio-org.atlassian.net/browse/UILD-261](https://folio-org.atlassian.net/browse/UILD-261)
> UILD-261: hide a default Note type on UI

- src/components/EditPreview/EditPreview.tsx
[https://folio-org.atlassian.net/browse/UILD-257](https://folio-org.atlassian.net/browse/UILD-257)
> UILD-257: disable "Add instance" button

- src/common/constants/feature.constants.ts
- src/components/EditControlPane/EditControlPane.tsx
- src/components/SearchResultEntry/SearchResultEntry.tsx
- src/components/WorkDetailsCard/WorkDetailsCard.tsx
[https://folio-org.atlassian.net/browse/UILD-260](https://folio-org.atlassian.net/browse/UILD-260)
> UILD-260: disable features for Alpha

- src/common/constants/bibframeMapping.constants.ts
[https://folio-org.atlassian.net/browse/UILD-191](https://folio-org.atlassian.net/browse/UILD-191)
> UILD-191: Update mapping for Content type field

- src/components/Button/Button.scss
- src/components/DuplicateGroup/DuplicateGroup.tsx
[https://folio-org.atlassian.net/browse/UILD-264](https://folio-org.atlassian.net/browse/UILD-264)
> UILD-264: Disable trash icon

- src/common/constants/bibframe.constants.ts
- src/common/constants/bibframeMapping.constants.ts
- src/common/helpers/recordFormatting.helper.ts
- src/test/__tests__/common/helpers/recordFormatting.helper.test.ts
[https://folio-org.atlassian.net/browse/UILD-136](https://folio-org.atlassian.net/browse/UILD-136)
> UILD-136: API contract changes for Place of publication 

- src/common/constants/bibframe.constants.ts
- src/common/services/recordNormalizing/recordProcessingCases.ts
- src/common/services/userValues/userValueTypes/simpleLookup.ts
- src/test/__tests__/common/services/recordNormalizing/recordProcessingCases.test.ts
[https://folio-org.atlassian.net/browse/UILD-267](https://folio-org.atlassian.net/browse/UILD-267)
> UILD-267: save value for Language code subfield

- src/common/constants/bibframe.constants.ts
- src/common/constants/bibframeMapping.constants.ts
- src/common/constants/search.constants.ts
- src/common/helpers/recordFormatting.helper.ts
- src/components/WorkDetailsCard/WorkDetailsCard.tsx
- src/test/__tests__/common/helpers/recordFormatting.helper.test.ts
[https://folio-org.atlassian.net/browse/UILD-270](https://folio-org.atlassian.net/browse/UILD-270)
> UILD-270: Classification number field value is not saved

- src/common/constants/uiElements.constants.ts
- src/components/EditSection/EditSection.tsx
- src/components/SimpleLookupField/SimpleLookupField.tsx
- src/test/__mocks__/lib/window.mock.ts
- src/test/__mocks__/setupMocks.ts
https://folio-org.atlassian.net/browse/UILD-272
> feat: UILD-272: Expand Language drop down UP

- src/common/constants/routes.constants.ts
- src/common/helpers/search.helper.ts
- src/common/hooks/useBackToSearchUri.ts
- src/common/hooks/useLoadSearchResults.ts
- src/common/hooks/usePagination.ts
- src/common/hooks/useSearchNavigationState.ts
- src/components/ItemSearch/ItemSearch.tsx
- src/test/__tests__/common/hooks/usePagination.test.ts
- src/test/__tests__/common/hooks/useSearchNavigationState.test.ts
- src/test/__tests__/components/ItemSearch.test.tsx
- src/types/search.d.ts
[https://folio-org.atlassian.net/browse/UILD-262](https://folio-org.atlassian.net/browse/UILD-262)
> UILD-262: back to required search results page

- src/components/SearchControls/SearchControls.tsx
- src/test/__tests__/components/SearchControls.test.tsx
[https://folio-org.atlassian.net/browse/UILD-265](https://folio-org.atlassian.net/browse/UILD-265)
> UILD-265: enable Reset button after conducting Advanced search

- src/common/constants/bibframe.constants.ts
- src/common/constants/bibframeMapping.constants.ts
- src/common/helpers/recordFormatting.helper.ts
- src/common/services/recordNormalizing/recordProcessingCases.ts
- src/common/services/recordNormalizing/recordProcessingMap.ts
- src/test/__tests__/common/helpers/recordFormatting.helper.test.ts
- src/test/__tests__/common/services/recordNormalizing/recordProcessingCases.test.ts
[https://folio-org.atlassian.net/browse/UILD-277](https://folio-org.atlassian.net/browse/UILD-277)
> UILD-277: apply new API contract for Statement of Responsibility

- src/test/__tests__/common/api/profiles.api.test.ts
[https://folio-org.atlassian.net/browse/UILD-31](https://folio-org.atlassian.net/browse/UILD-31)
> UILD-31: unit tests for profiles.api

- src/test/__tests__/common/hooks/useConfig.hook.test.ts
[https://folio-org.atlassian.net/browse/UILD-37](https://folio-org.atlassian.net/browse/UILD-37)
> UILD-37: unit tests for useConfig hook

- src/common/constants/bibframeMapping.constants.ts
- src/common/constants/lookup.constants.ts
- src/common/services/recordNormalizing/recordProcessingCases.ts
- src/common/services/recordNormalizing/recordProcessingMap.ts
- src/common/services/userValues/userValueTypes/complexLookup.ts
- src/components/ComplexLookupField/ComplexLookupField.tsx
- src/components/EditSection/EditSection.tsx
- src/test/__tests__/common/services/recordNormalizing/recordProcessingCases.test.ts
- src/types/recordProcessing.d.ts
[https://folio-org.atlassian.net/browse/UILD-296](https://folio-org.atlassian.net/browse/UILD-296)
> UILD-296: API contract for LC classification

- src/common/hooks/useConfig.hook.ts
- src/common/hooks/useRecordControls.ts
- src/components/FullDisplay/FullDisplay.scss
- src/components/FullDisplay/FullDisplay.tsx
- src/components/ItemSearch/ItemSearch.scss
- src/components/ItemSearch/ItemSearch.tsx
- src/components/SearchControlPane/SearchControlPane.scss
- src/components/SearchResultEntry/SearchResultEntry.scss
- src/components/SearchResultEntry/SearchResultEntry.tsx
- src/components/SearchResultList/SearchResultList.scss
- src/components/Table/Table.scss
- src/components/Table/Table.tsx
- src/types/record.d.ts
https://folio-org.atlassian.net/browse/UILD-268
> feat: UILD-268: Story: Full Display of single instance - search results panel

- src/common/constants/bibframeMapping.constants.ts
[https://folio-org.atlassian.net/browse/UILD-297](https://folio-org.atlassian.net/browse/UILD-297)
[https://folio-org.atlassian.net/browse/UILD-307](https://folio-org.atlassian.net/browse/UILD-307)
> UILD-297: Dewey Classification - Use new API contract

- src/common/constants/bibframeMapping.constants.ts
[https://folio-org.atlassian.net/browse/UILD-324](https://folio-org.atlassian.net/browse/UILD-324)
> UILD-324: Fixed mapping for Description Source

- src/components/AdvancedSearchModal/AdvancedSearchModal.scss
- src/components/SearchControls/SearchControls.scss
https://folio-org.atlassian.net/browse/UILD-290
> fix: UILD-290: BUG: Search field: cursor is not shown at the end of long search term

- src/common/constants/record.constants.ts
- src/common/hooks/useRecordControls.ts
- src/components/EditControlPane/EditControlPane.tsx
- src/components/RecordControls/RecordControls.tsx
- src/components/SaveRecord/SaveRecord.tsx
- src/state/status.ts
- src/test/__tests__/components/SaveRecord.test.tsx
- src/types/record.d.ts
- src/views/Edit/Edit.tsx
[https://folio-org.atlassian.net/browse/UILD-298](https://folio-org.atlassian.net/browse/UILD-298)
> UILD-298: save and keep editing

- src/common/constants/lookup.constants.ts
- src/common/helpers/lookupOptions.helper.ts
- src/common/services/userValues/userValueTypes/simpleLookup.ts
- src/components/Preview/Preview.tsx
- src/test/__tests__/common/helpers/lookupOptions.helper.test.ts
- src/types/render.d.ts
[https://folio-org.atlassian.net/browse/UILD-322](https://folio-org.atlassian.net/browse/UILD-322)
> UILD-322: lookup options codes

- src/common/constants/bibframeMapping.constants.ts
- src/common/helpers/record.helper.ts
- src/components/EditPreview/EditPreview.scss
- src/components/Preview/Preview.scss
- src/components/Preview/Preview.tsx
- src/components/Prompt/Prompt.tsx
https://folio-org.atlassian.net/browse/UILD-283
> feat: UILD-283: STORY: Transportation Instance Edit Screen

- src/common/constants/bibframe.constants.ts
- src/common/constants/bibframeMapping.constants.ts
- src/common/services/recordNormalizing/recordProcessingCases.ts
- src/test/__tests__/common/services/recordNormalizing/recordProcessingCases.test.ts
[https://folio-org.atlassian.net/browse/UILD-331](https://folio-org.atlassian.net/browse/UILD-331)
> UILD-331: apply API contract to Language field

- src/components/Preview/Preview.tsx
https://folio-org.atlassian.net/browse/UILD-283?focusedCommentId=219000
> fix: UILD-283: bypass record status block when switching between work and instance

- src/common/helpers/profile.helper.ts
- src/common/services/userValues/userValueTypes/simpleLookup.ts
- src/components/SimpleLookupField/SimpleLookupField.tsx
[https://folio-org.atlassian.net/browse/UILD-322](https://folio-org.atlassian.net/browse/UILD-322)
> UIKD-322: fix for saving and loading options with codes

- src/common/api/search.api.ts
[https://folio-org.atlassian.net/browse/UILD-334](https://folio-org.atlassian.net/browse/UILD-334)
> UILD-334: Update API URI for search endpoint

- src/common/constants/lookup.constants.ts
- src/common/helpers/lookupOptions.helper.ts
[https://folio-org.atlassian.net/browse/UILD-335](https://folio-org.atlassian.net/browse/UILD-335)
> UILD-335: show labels in Lookup options

- src/components/MarcField/MarcField.tsx
[https://folio-org.atlassian.net/browse/UILD-331](https://folio-org.atlassian.net/browse/UILD-331)
> UILD-331: checking for empty value in MARC view mode

- src/common/services/schema/schemaWithDuplicates.service.ts
- src/test/__tests__/common/services/schema/schemaWithDuplicates.service.test.ts
[https://folio-org.atlassian.net/browse/UILD-318](https://folio-org.atlassian.net/browse/UILD-318)
> UILD-318: duplicate a subcomponent with empty value

- src/common/services/recordToSchemaMapping/recordToSchemaMapping.service.ts
- src/views/Edit/Edit.tsx
[https://folio-org.atlassian.net/browse/UILD-318](https://folio-org.atlassian.net/browse/UILD-318)
> fix: UILD-318: restoring repeatable subcomponents after loading a saved record

- package-lock.json
- src/components/Preview/Preview.tsx
- src/components/PreviewActionsDropdown/PreviewActionsDropdown.tsx
https://folio-org.atlassian.net/browse/UILD-273
> feat: UILD-273: STORY: Transportation Work Edit Screen

- src/App.scss
- src/common/constants/bibframeMapping.constants.ts
- src/common/helpers/recordFormatting.helper.ts
- src/common/services/schema/schema.service.ts
- src/components/ComplexLookupField/ComplexLookupField.scss
- src/components/ComplexLookupField/ComplexLookupField.tsx
- src/components/ComplexLookupField/ModalComplexLookup.scss
- src/components/ComplexLookupField/ModalComplexLookup.tsx
- src/components/EditSection/EditSection.tsx
- src/components/Modal/Modal.tsx
- src/test/__tests__/common/helpers/recordFormatting.helper.test.ts
- src/test/__tests__/components/ComplexLookupField.test.tsx
- src/types/bibframeProfile.d.ts
- src/types/render.d.ts
[https://folio-org.atlassian.net/browse/UILD-344](https://folio-org.atlassian.net/browse/UILD-344)
> UILD-344: Authority selection display

- src/common/hooks/useSearchFilters.ts
- src/components/ComplexLookupField/ComplexLookupField.tsx
- src/components/ComplexLookupField/ModalComplexLookup.scss
- src/components/ComplexLookupField/ModalComplexLookup.tsx
- src/state/search.ts
- src/test/__tests__/common/hooks/useSearchFilters.test.tsx
- src/test/__tests__/components/ComplexLookupField.test.tsx
- src/types/select.d.ts
[https://folio-org.atlassian.net/browse/UILD-346](https://folio-org.atlassian.net/browse/UILD-346)
> UILD-346: unit tests for Complex lookups and search filters

- src/common/helpers/recordFormatting.helper.ts
- src/test/__tests__/common/helpers/recordFormatting.helper.test.ts
[https://folio-org.atlassian.net/browse/UILD-351](https://folio-org.atlassian.net/browse/UILD-351)
> UILD-351: Save a record without Relationship value

- src/common/i18n/messages.ts
- src/components/ComplexLookupField/ModalComplexLookup.tsx
- src/components/SearchControls/SearchControls.tsx
[https://folio-org.atlassian.net/browse/UILD-344](https://folio-org.atlassian.net/browse/UILD-344)
> UILD-344: fix for labels

- src/components/EditPreview/EditPreview.tsx
- src/components/Preview/Preview.scss
- src/components/Preview/Preview.tsx
- src/components/Prompt/Prompt.tsx
- src/components/RecordControls/RecordControls.tsx
https://folio-org.atlassian.net/browse/UILD-349
> feat: UILD-349: STORY - UI updates to LDE

- src/common/i18n/messages.ts
- src/components/FullDisplay/FullDisplay.scss
- src/components/FullDisplay/FullDisplay.tsx
- src/components/SearchResultEntry/SearchResultEntry.tsx
- src/components/WorkDetailsCard/WorkDetailsCard.tsx
- src/test/__tests__/components/FullDisplay.test.tsx
https://folio-org.atlassian.net/browse/UILD-350
> feat: UILD-350: STORY: Full Display of work - search results panel

- src/common/helpers/complexLookup.helper.ts
- src/common/hooks/useComplexLookup.ts
- src/components/SearchControls/SearchControls.tsx
[https://folio-org.atlassian.net/browse/UILD-347](https://folio-org.atlassian.net/browse/UILD-347)
> UILD-347: fix default "Select by" option and selected dropdown options

- src/common/hooks/useSearch.ts
- src/components/WorkDetailsCard/WorkDetailsCard.scss
[https://folio-org.atlassian.net/browse/UILD-347](https://folio-org.atlassian.net/browse/UILD-347)
> UILD-347: fix for search results styling and default "Search by" option

- src/common/constants/domElementsIdentifiers.constants.ts
- src/components/ComplexLookupField/ModalComplexLookup.scss
- src/components/ItemSearch/ItemSearch.tsx
[https://folio-org.atlassian.net/browse/UILD-347](https://folio-org.atlassian.net/browse/UILD-347)
> UILD-347: add padding to the search messages

- src/common/hooks/useLookupCache.hook.ts
- src/common/hooks/useSimpleLookupData.ts
- src/common/services/userValues/userValueTypes/simpleLookup.ts
- src/common/services/userValues/userValues.service.ts
- src/components/SimpleLookupField/SimpleLookupField.tsx
- src/contexts/ServicesContext.ts
- src/providers/ServicesProvider.tsx
- src/state/config.ts
- src/test/__mocks__/providers/ServicesProvider.mock.tsx
- src/test/__tests__/common/hooks/useSimpleLookupData.test.tsx
- src/types/serviceContext.d.ts
[https://folio-org.atlassian.net/browse/UILD-364](https://folio-org.atlassian.net/browse/UILD-364)
[https://folio-org.atlassian.net/browse/UILD-365](https://folio-org.atlassian.net/browse/UILD-365)
[https://folio-org.atlassian.net/browse/UILD-367](https://folio-org.atlassian.net/browse/UILD-367)
> UILD-365: fix for incorrect lookup values and fields selection

- src/common/hooks/useConfig.hook.ts
[https://folio-org.atlassian.net/browse/UILD-363](https://folio-org.atlassian.net/browse/UILD-363)
> UILD-363: Fix for Preview: set the correct record data

- src/common/constants/record.constants.ts
- src/common/constants/resourceTemplates.constants.ts
- src/common/constants/routes.constants.ts
- src/common/helpers/bibframe.helper.ts
- src/common/helpers/navigation.helper.ts
- src/common/helpers/recordFormatting.helper.ts
- src/common/helpers/schema.helper.ts
- src/common/hooks/useConfig.hook.ts
- src/common/hooks/useNavigateToEditPage.ts
- src/common/hooks/useRecordControls.ts
- src/common/i18n/messages.ts
- src/common/services/recordToSchemaMapping/recordToSchemaMapping.service.ts
- src/common/services/userValues/userValues.interface.ts
- src/components/EditControlPane/EditControlPane.tsx
- src/components/EditSection/EditSection.tsx
- src/components/Preview/Preview.tsx
- src/components/PreviewActionsDropdown/PreviewActionsDropdown.tsx
- src/components/Prompt/Prompt.tsx
- src/test/__tests__/components/FullDisplay.test.tsx
- src/types/bibframeProfile.d.ts
- src/types/record.d.ts
- src/types/render.d.ts
- src/views/Edit/Edit.tsx
https://folio-org.atlassian.net/browse/UILD-333
> feat: UILD-333: STORY: Duplicate Instance

- src/common/hooks/useSearch.ts
https://folio-org.atlassian.net/browse/UILD-366
> feat: UILD-366: Close full view side bar after performing search or clicking reset

- src/common/hooks/useConfig.hook.ts
- src/state/config.ts
- src/test/__tests__/common/hooks/useConfig.hook.test.ts
[https://folio-org.atlassian.net/browse/UILD-377](https://folio-org.atlassian.net/browse/UILD-377)
> UILD-377: prevent unnecessary loading and processing of the profile

- src/test/__tests__/common/services/recordToSchemaMapping/recordToSchemaMapping.service.test.ts
[https://folio-org.atlassian.net/browse/UILD-378](https://folio-org.atlassian.net/browse/UILD-378)
> UILD-378: fix for broken unit tests

- src/components/Preview/Preview.tsx
[https://folio-org.atlassian.net/browse/UILD-355](https://folio-org.atlassian.net/browse/UILD-355)
> UILD-355: display Subclass in Preview

- src/components/SimpleLookupField/SimpleLookupField.tsx
[https://folio-org.atlassian.net/browse/UILD-339](https://folio-org.atlassian.net/browse/UILD-339)
> UILD-339: fix for Simple lookups filtering

- src/common/helpers/dom.helper.ts
- src/common/hooks/useContainerEvents.ts
- src/common/hooks/useRecordControls.ts
- src/components/EditSection/EditSection.tsx
- src/components/Prompt/Prompt.tsx
- src/test/__tests__/common/helpers/dom.helper.test.ts
- src/test/__tests__/common/hooks/useContainerEvents.test.ts
- src/test/__tests__/components/Prompt.test.tsx
- src/test/__tests__/components/SearchResultEntry.test.tsx
- src/test/__tests__/components/SearchResultList.test.tsx
https://folio-org.atlassian.net/browse/UILD-381
> fix: UILD-381: Inventory button doesn't work after saving changes in LDE

- src/common/hooks/useRecordControls.ts
- src/common/hooks/useRecordStatus.ts
- src/components/DeleteRecord/DeleteRecord.tsx
- src/components/SaveRecord/SaveRecord.tsx
- src/state/status.ts
- src/test/__tests__/common/hooks/useRecordStatus.test.ts
- src/test/__tests__/components/SaveRecord.test.tsx
https://folio-org.atlassian.net/browse/UILD-371
> fix: UILD-371: Keep save buttons active after first save

- package-lock.json
- src/common/hooks/usePagination.ts
> fix: incorrect condition

- src/common/hooks/useLoadSearchResults.ts
- src/common/hooks/useSearch.ts
https://folio-org.atlassian.net/browse/UILD-383
> fix: UILD-383: TEST ONLY - BUG fix for LCCN query normalization

- src/components/SearchResultEntry/SearchResultEntry.tsx
- src/components/WorkDetailsCard/WorkDetailsCard.tsx
- src/test/__tests__/components/ItemSearch.test.tsx
- src/test/__tests__/components/SearchResultEntry.test.tsx
- src/test/__tests__/components/SearchResultList.test.tsx
- src/types/api.d.ts
[https://folio-org.atlassian.net/browse/UILD-388](https://folio-org.atlassian.net/browse/UILD-388)
> UILD-388: Migrate to new Search DTO

- src/App.scss
- src/components/Button/Button.scss
https://folio-org.atlassian.net/browse/UILD-389
> tech: UILD-389: [tech debt]: fix SCSS Deprecation Warnings

- src/common/hooks/useSearch.ts
[https://folio-org.atlassian.net/browse/UILD-375](https://folio-org.atlassian.net/browse/UILD-375)
[https://folio-org.atlassian.net/browse/UILD-369](https://folio-org.atlassian.net/browse/UILD-369)
> UILD-375: fix for displaying message "No resource descriptions match your request"

- src/common/constants/bibframe.constants.ts
- src/common/helpers/schema.helper.ts
- src/common/services/schema/entryPropertiesGenerator.interface.ts
- src/common/services/schema/entryPropertiesGenerator.service.ts
- src/common/services/schema/schema.service.ts
- src/common/services/schema/schemaWithDuplicates.service.ts
- src/components/ComplexLookupField/ComplexLookupField.tsx
- src/components/DropdownField/DropdownField.tsx
- src/components/EditSection/EditSection.tsx
- src/components/LiteralField/LiteralField.tsx
- src/components/Preview/Preview.tsx
- src/components/Select/Select.tsx
- src/components/SimpleLookupField/SimpleLookupField.tsx
- src/providers/ServicesProvider.tsx
- src/test/__tests__/common/services/schema/schemaWithDuplicates.service.test.ts
- src/types/render.d.ts
https://folio-org.atlassian.net/browse/UILD-390
> feat: UILD-390: Implement Unique Selectors for E2E Testing

- src/test/__tests__/common/helpers/schema.helper.test.ts
- src/test/__tests__/common/services/schema/entryPropertiesGenerator.service.test.ts
https://folio-org.atlassian.net/browse/UILD-390
> unit: UILD-390: Implement Unique Selectors for E2E Testing

- src/common/constants/bibframe.constants.ts
- src/common/constants/uiControls.constants.ts
- src/common/helpers/schema.helper.ts
- src/common/services/schema/schema.service.ts
- src/components/Button/Button.tsx
- src/components/ComplexLookupField/ComplexLookupField.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/DropdownField/DropdownField.tsx
- src/components/DuplicateGroup/DuplicateGroup.tsx
- src/components/EditSection/EditSection.tsx
- src/components/FieldWithMetadataAndControls/CompactLayout.tsx
- src/components/FieldWithMetadataAndControls/ExtendedLayout.tsx
- src/components/FieldWithMetadataAndControls/FieldWithMetadataAndControls.tsx
- src/components/LiteralField/LiteralField.tsx
- src/components/PreviewActionsDropdown/PreviewActionsDropdown.tsx
- src/components/SearchResultEntry/SearchResultEntry.tsx
- src/components/SimpleLookupField/SimpleLookupField.tsx
- src/components/WorkDetailsCard/WorkDetailsCard.tsx
- src/test/__tests__/components/DuplicateGroup.test.tsx
- src/test/__tests__/components/EditSection.test.tsx
- src/test/__tests__/components/SearchResultEntry.test.tsx
- src/views/Search/Search.tsx
https://folio-org.atlassian.net/browse/UILD-390?focusedCommentId=230274
> feat: UILD-390: add htmlId generation for schema controls

- src/common/constants/resourceTemplates.constants.ts
- src/common/helpers/record.helper.ts
- src/common/hooks/useProcessedRecordAndSchema.hook.ts
- src/components/EditControlPane/EditControlPane.tsx
- src/components/EditPreview/EditPreview.tsx
- src/views/Edit/Edit.tsx
https://folio-org.atlassian.net/browse/UILD-220
> feat: UILD-220: STORY: Duplicate Work

- src/App.tsx
- src/common/constants/routes.constants.ts
- src/common/i18n/messages.ts
- src/components/ExternalResourceLoader/ExternalResourceLoader.scss
- src/components/ExternalResourceLoader/ExternalResourceLoader.tsx
- src/components/ExternalResourceLoader/index.ts
- src/views/ExternalResource/ExternalResourceEdit.tsx
- src/views/ExternalResource/index.ts
- src/views/index.tsx
https://folio-org.atlassian.net/browse/UIIN-3052
> feat: UIIN-3052: STORY: Enabling 'Edit in linked data editor' option in Inventory Actions drop down menu

- src/common/api/search.api.ts
- src/common/constants/complexLookup.constants.ts
- src/common/constants/search.constants.ts
- src/common/helpers/search/queryBuilder/index.ts
- src/common/helpers/search/queryBuilder/queryBuilder.ts
- src/common/hooks/useComplexLookup.ts
- src/common/hooks/useSearch.ts
- src/components/ComplexLookupField/ComplexLookupSearchResults.tsx
- src/components/ComplexLookupField/MarсPreviewComplexLookup.tsx
- src/components/ComplexLookupField/ModalComplexLookup.scss
- src/components/ComplexLookupField/ModalComplexLookup.tsx
- src/configs/complexLookup/complexLookup.config.ts
- src/configs/complexLookup/complexLookupSeachableIndicesMap.ts
- src/configs/complexLookup/complexLookupSearchBy.config.ts
- src/contexts/SearchContext.ts
- src/types/complexLookup.d.ts
- src/types/search.d.ts
[https://folio-org.atlassian.net/browse/UILD-395](https://folio-org.atlassian.net/browse/UILD-395)
> UILD-395: generate search query parameters for Authorities Search API

- package-lock.json
- src/components/Preview/Preview.tsx
https://folio-org.atlassian.net/browse/UILD-379
> feat: UILD-379: STORY : Open links from full view side-bars in new browser tab

- src/components/CommonStatus/CommonStatus.scss
- src/components/Loading/Loading.scss
- src/components/Modal/Modal.scss
- src/components/Textarea/Textarea.scss
[https://folio-org.atlassian.net/browse/UILD-392](https://folio-org.atlassian.net/browse/UILD-392)
[https://folio-org.atlassian.net/browse/UILD-395](https://folio-org.atlassian.net/browse/UILD-395)
> UILD-395: Authorities lookup - layout fixes

- src/components/ModalSwitchToNewRecord/ModalSwitchToNewRecord.tsx
https://folio-org.atlassian.net/browse/UILD-386
> fix: UILD-386: "Continue without saving" is disabled while switching back to work from "create new instance" screen

- src/common/constants/domElementsIdentifiers.constants.ts
- src/components/ComplexLookupField/ComplexLookupSearchResults.tsx
- src/components/ComplexLookupField/ModalComplexLookup.scss
- src/components/ComplexLookupField/configs/Authorities.tsx
- src/components/Table/Table.scss
- src/components/Table/TableFlex.tsx
- src/components/Table/index.ts
- src/components/Textarea/Textarea.scss
[https://folio-org.atlassian.net/browse/UILD-392](https://folio-org.atlassian.net/browse/UILD-392)
> UILD-392: add Table component with flexible layout

- src/common/constants/uiElements.constants.ts
- src/components/ComplexLookupField/MarсPreviewComplexLookup.scss
- src/components/ComplexLookupField/MarсPreviewComplexLookup.tsx
- src/components/ComplexLookupField/ModalComplexLookup.scss
- src/components/Table/TableFlex.tsx
[https://folio-org.atlassian.net/browse/UILD-392](https://folio-org.atlassian.net/browse/UILD-392)
> UILD-392: Authorities search modal - styles fix
